### ISSUE TITLE
"ValueError: too many values to unpack (expected 2)" - pipeline.fit(), pointing at data.train_Y

### ISSUE THREAD

**Issue by NJHitch1990** [SoniaLei/nlp-web-scrapping#25]
When trying to run 'run.py' file with:
- configuration = experiment001.yml
- probabilities = True
The above error comes up:
- ValueError: too many values to unpack (expected 2)

The error page, attached to Issue, points to the data.train_Y:
- pipeline_fitted = self.pipeline.fit(self.data.train_X,
                                                      self.data.train_Y)
'Seems' to be an issue with the data

![Issue_run](https://user-images.githubusercontent.com/54172766/86898476-a9229c80-c100-11ea-98bc-76403bde7a45.png)
![Issue_error](https://user-images.githubusercontent.com/54172766/86899375-d754ac00-c101-11ea-896f-af72f1997351.png)

**Comment by alwaysfish** [comment]
What is the content of experiment001.yml file?

**Comment by NJHitch1990** [comment]
# Block commenting of YAML files in VSCode and PyCharm can be achieved
# by selecting lines and using shortcut Ctrl + /


# Location of data files
data_files:
  train: "https://raw.githubusercontent.com/SoniaLei/nlp-web-scrapping/development/data/raw/tweets-train.csv"
  test: "https://raw.githubusercontent.com/SoniaLei/nlp-web-scrapping/development/data/raw/tweets-test.csv"
  features: "text"
  target: "sentiment"


transformers:
  - DummyTransformer:

vectorizers:
  - TfidfVectorizer:
      stop_words: None
      max_features: 10000
      ngram_range: (1, 1)

estimators:
  - LogisticRegression:
      penalty: l2
      max_iter: 100
      n_jobs: -1

**Comment by NJHitch1990** [comment]
When i run the file with:
- probabilities = False
the same error occurs

**Comment by alwaysfish** [comment]
Fixed by the overhauled pipeline
