### ISSUE TITLE
Exception when running an experiment on 'pipeline' branch

### ISSUE THREAD

**Issue by alwaysfish** [SoniaLei/nlp-web-scrapping#27]
Try to run the following experiment on 'pipeline' branch:
data:
  train: "https://raw.githubusercontent.com/SoniaLei/nlp-web-scrapping/development/data/raw/tweets-train.csv"
  test: "https://raw.githubusercontent.com/SoniaLei/nlp-web-scrapping/development/data/raw/tweets-test.csv"
  features: "text"
  target: "sentiment"

vectorizers:
  CountVectorizer:

estimators:
  MultinomialNB:
    cv: 3
    params:
  SVC:
    cv: 3
    params:
      probability: True

A runtime exception occurs on Experiment.save_to_mlflow() function, saying that access is denied to folder 'C:\\Users\\Elia'

![image](https://user-images.githubusercontent.com/10214130/87233201-46a9f480-c3bd-11ea-993e-9dd1cb716068.png)

**Comment by eliaborras** [comment]
Good Morning Ernest, 

This is all about how mlflow gets url to save artifacts.
I'll need to "properly" have a look in to it. 
I believe there is an issue with how we set -> mlflow.set_tracking_uri()

The question is:
In the picture, Line 49 does not give you any bug right?
so the uri path for that one is correct and gives error when inside the with block. 

I'll Look into it for sure. 

Thanks for that

Elia

**Comment by alwaysfish** [comment]
Fixed by the overhauled pipeline
