### ISSUE TITLE
Running exp014 and exp015 using Word2Vec Vectorizer. Branch: pipeline

### ISSUE THREAD

**Issue by eliaborras** [SoniaLei/nlp-web-scrapping#29]
**Ticket in planner: Ta6.5.1 -Test overhauled MLpipeline**

Attempt running Experiments: 
exp014  -> Tokenizer + Word2Vec Vectorizer + LogisticRegression  
exp015 -> Tokenizer + Word2Vec Vectorizer + GradientBoosting  

Error Log: 
![image](https://user-images.githubusercontent.com/38831184/87638843-5a968300-c73c-11ea-8972-e892975ef24d.png)

**Comment by alwaysfish** [comment]
The issue has been resolved with the latest updates inside pipeline branch
