### ISSUE TITLE
[original stocktwets data extractor] UnicodeEncodeError for windows 10

### ISSUE THREAD

**Issue by eliaborras** [SoniaLei/nlp-web-scrapping#33]
When runing the script this occurs:
![image](https://user-images.githubusercontent.com/38831184/88141176-fddb1280-cbea-11ea-897a-45dbc4d25883.png)

I commented out line 94 when does the printing, and the scraper works. 

Found the issue in:
https://stackoverflow.com/questions/5419/python-unicode-and-the-windows-console
Seems the issue is just for windows users?

Logging this as informative.
original scraper file does not need fixing/changes for this matter at this point.

**Comment by alwaysfish** [comment]
Closing, as it is not reproducable any more.
